sudo: false
dist: trusty
env:
  global:
    - GRADLE_USER_HOME=gradle-cache
language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - gradle-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

branches:
  except:
    - /^[0-9]/

install:
  - ./gradlew assemble

script:
  - ./gradlew check

#after_success:
#  - '[ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ./gradlew bintrayUpload || :'

